/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],



  // But you can create a sidebar manually
  
 ccoeSidebar: [
    {
      type: 'category',
      label: 'FinOps',
      items: ['CCOE-doc/Finops', 'CCOE-doc/testpage'],
      // 'CCOE-docs/test-page' is an existing page,
      // 'CCOE-docs/new-page' is the path to your new page
    },
    {
      type: 'category',
      label: 'Platform',
      items: ['Platform/1-B2B Portal'],
      // 'CCOE-docs/test-page' is an existing page,
      // 'CCOE-docs/new-page' is the path to your new page
    },
  ],
  introSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['Introduction/Intro'],
      // 'CCOE-docs/test-page' is an existing page,
      // 'CCOE-docs/new-page' is the path to your new page
    },
  ],
   
};


export default sidebars;
